# Generated by Django 3.1.1 on 2020-09-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bme280Sensor',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('temp', models.IntegerField(blank=True, db_column='Temp', null=True)),
                ('pressure', models.IntegerField(blank=True, db_column='Pressure', null=True)),
                ('humidity', models.IntegerField(blank=True, db_column='Humidity', null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'BME280Sensor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Moisturesensor',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('moisture', models.IntegerField(blank=True, db_column='Moisture', null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'MoistureSensor',
                'managed': False,
            },
        ),
    ]
